- name: understanding precedence of variables
  hosts: all
  become: yes
    #  vars:
    #username: playuser
    #usercomment: variable user from playbook
  tasks:
    - name: creating a user "{{username}}" and "{{usercomment}}"
      user:
        name: "{{username}}"
        comment: "{{usercomment}}"
      register: USEROUT
    - debug:
        var: USEROUT.name
    - debug:
        var: USEROUT.comment
      
