---
# handlers file for post-install
- name: Restart RedHat ntp server
  service:
    name: ntpd
    state: restarted
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: Restart Debian ntp server
  service:
    name: systemd-timesyncd
    state: restarted
    enabled: yes
  when: ansible_os_family == "Debian"

