---

- name: Setup WebServer
  hosts: webservergrp
  become: yes
  tasks:
    - name: install Apache httpd
      yum:
        name: httpd
        state: present

    - name: Start & Enable httpd
      service:
        name: httpd
        state: started
        enabled: yes
    - name: deploy webfile - index.html -
      copy:
        src: index.html
        dest: /var/www/html/index.html


- name: Setup DBServer
  hosts: dbservergrp
  become: yes
  tasks:
    - name: Install MySQL server
      yum:
        name: mariadb-server
        state: present
          
    - name: Start and Enable SQL server
      service:
        name: mariadb
        state: started
        enabled: yes
