---
# tasks file for lamp-server
- name: Installing apache2 and mysql
  package:
    name: 
      - apache2
      - mysql-server
    state: latest

- name: Installing php
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - php
    - libapache2-mod-php
    - php-mysql