---

- name: Provisioning Server
  hosts: all
  become: yes
  tasks: 
    - name: Install ntp on Centos machines
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name:  Install ntp on ubuntu machine
      apt:
        name: systemd-timesyncd
        state: present
      when: ansible_distribution == "Ubuntu"
      loop:
        - systemd-timesyncd
        - wget
        - git 
        - zip
        - unzip
  
    - name: Start ntp server and enable it
      service:
        name: ntpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Start & enable NTP on debian
      service:
        name: systemd-timesyncd
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: adding groups
      group:
        name: "{{item}}"
        state: present 
      loop:
          - hamza-g1
          - hamza-g2

    - name: addng user
      user:
        name: "{{item}}"
        comment: "full name is still unknown"
      loop:
          - hamza-u1
          - hamza-u2

    - name: banner file /etc/motd
      copy:
          content: "this {{ansible_distribution}} is managed by ansible \n"
          dest: /etc/motd

    - name: copy files from current dir into other host machines
      template:
        src: ./templates/hamza-ansible-file.j2
        dest: /home/centos/hamza_file
      when: ansible_os_family == "RedHat"

    - name: copy files from current dir into other debian host machines
      template:
        src: ./templates/hamza-ansible-file.j2
        dest: /home/ubuntu/hamza_file
      when: ansible_os_family == "Debian"

    - name: Restart ntp server
      service:
        name: ntpd
        state: restarted
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Restart ntp server
      service:
        name: systemd-timesyncd
        state: restarted
        enabled: yes
      when: ansible_os_family == "Debian"


