---

- name: Provisioning Server
  hosts: all
  become: yes
  tasks: 
    - name: Install ntp on Centos machines
      yum:
        name: "{{item}}"
        state: present
      when: ansible_distribution == "CentOS"
      loop:
        - ntp
        - wget
        - git
        - zip
        - unzip

    - name:  Install ntp on ubuntu machine
      apt:
        name: systemd-timesyncd
        state: present
      when: ansible_distribution == "Ubuntu"
      loop:
        - systemd-timesyncd
        - wget
        - git 
        - zip
        - unzip
  
    - name: Start ntp server and enable it
      service:
        name: ntpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Start & enable NTP on debian
      service:
        name: systemd-timesyncd
        state: started
        enabled: yes
      when: ansible_os_family == "Debian"

    - name: adding groups
      group:
        name: "{{item}}"
        state: present 
      loop:
          - hamza-g1
          - hamza-g2
    - name: addng user
      user:
        name: johnd
        comment: "full name is still unknown"
      loop:
          - hamza-u1
          - hamza-u2

